---
stages:
  - docker
  - post

variables:
  DOCKER_IMAGE_NAME: cenk1cenk2/ansible-core
  IMAGE_TAGS: latest
  README_DESCRIPTION: |
    Run Ansible in Docker with NodeJS installed.
  BUILD_ARGS: S6_VERSION=2.2.0.3,NODE_VERSION=18-bullseye-slim,PYTHON_VERSION=3.11.0-slim-bullseye,ANSIBLE_VERSION=7.1.0

include:
  - project: devops/pipes
    file: /templates/docker-build-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/update-docker-hub-readme.gitlab-ci.yml
